// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0nsCvvVrPxE8ee6yW4mBOjM5luoQVLo',
    appId: '1:256827687821:web:d81cb9331c8a45957333c4',
    messagingSenderId: '256827687821',
    projectId: 'trioangle-a3d9c',
    authDomain: 'trioangle-a3d9c.firebaseapp.com',
    storageBucket: 'trioangle-a3d9c.appspot.com',
    measurementId: 'G-R3ZXF0NZTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92UOa8_58kQX1K4UfCL8r7cM7I19WpAs',
    appId: '1:256827687821:android:a80fef5f64f6110c7333c4',
    messagingSenderId: '256827687821',
    projectId: 'trioangle-a3d9c',
    storageBucket: 'trioangle-a3d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMeCQjQPEVlmcU7C-8sCNCpEKQisHrvQ',
    appId: '1:256827687821:ios:3f8c8d4478fa31c67333c4',
    messagingSenderId: '256827687821',
    projectId: 'trioangle-a3d9c',
    storageBucket: 'trioangle-a3d9c.appspot.com',
    iosBundleId: 'com.example.trioangle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMeCQjQPEVlmcU7C-8sCNCpEKQisHrvQ',
    appId: '1:256827687821:ios:0e989497aa6229c87333c4',
    messagingSenderId: '256827687821',
    projectId: 'trioangle-a3d9c',
    storageBucket: 'trioangle-a3d9c.appspot.com',
    iosBundleId: 'com.example.trioangle.RunnerTests',
  );
}
